name: chainbase-node Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-n-publish-to-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17.0"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://chainbase-registry.ap-southeast-1.cr.aliyuncs.com
          region-id: "ap-southeast-1"
          access-key-id: "${{ secrets.ALI_ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ALI_ACCESS_KEY_SECRET }}"
          instance-id: "cri-a4wmsz77ru5o7hub"

      - name: Build and push docker image to ACR
        uses: docker/build-push-action@v4
        env:
          REGISTRY: chainbase-registry.ap-southeast-1.cr.aliyuncs.com/network
          REPOSITORY: chainbase-node
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
